'use client'
import { useState, useRef } from 'react'
import { useStore } from '@/store/useStore'
import { Download, RotateCw } from 'lucide-react'
import { motion } from 'framer-motion'
import html2canvas from 'html2canvas'

export function ActionMenu() {
    const { resetDay, tasks } = useStore()
    const [resetting, setResetting] = useState(false)
    const timeoutRef = useRef<NodeJS.Timeout | null>(null)

    const handleResetStart = () => {
        setResetting(true)
        timeoutRef.current = setTimeout(() => {
            resetDay()
            setResetting(false)
        }, 1500)
    }

    const handleResetEnd = () => {
        if (timeoutRef.current) clearTimeout(timeoutRef.current)
        setResetting(false)
    }

    const handleDownload = async () => {
        const report = document.createElement('div')
        Object.assign(report.style, {
            position: 'absolute',
            left: '-9999px',
            top: '0',
            width: '600px',
            background: '#000',
            color: '#fff',
            padding: '40px',
            fontFamily: 'sans-serif'
        })

        const date = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
        const completedCount = tasks.filter(t => t.completed).length
        const percentage = tasks.length === 0 ? 0 : Math.round((completedCount / tasks.length) * 100)

        report.innerHTML = `
      <div style="border: 2px solid #333; padding: 40px; border-radius: 20px;">
        <h1 style="font-size: 32px; font-weight: bold; margin: 0 0 10px 0; text-transform: uppercase; letter-spacing: 2px;">Daily Execution Report</h1>
        <p style="color: #666; margin: 0 0 40px 0; font-size: 18px;">${date}</p>
        
        <div style="display: flex; justify-content: space-between; margin-bottom: 40px; background: #111; padding: 20px; border-radius: 10px;">
          <div style="text-align: center;">
            <div style="font-size: 36px; font-weight: bold; color: #fff;">${percentage}%</div>
            <div style="color: #666; font-size: 12px; text-transform: uppercase;">Completion</div>
          </div>
          <div style="text-align: center;">
            <div style="font-size: 36px; font-weight: bold; color: #fff;">${completedCount}/${tasks.length}</div>
            <div style="color: #666; font-size: 12px; text-transform: uppercase;">Tasks Done</div>
          </div>
        </div>

        <ul style="list-style: none; padding: 0;">
          ${tasks.map(t => `
            <li style="margin-bottom: 12px; display: flex; align-items: center; color: ${t.completed ? '#888' : '#fff'};">
              <span style="display: inline-block; width: 20px; height: 20px; border: 2px solid ${t.completed ? '#0aff0a' : '#444'}; border-radius: 4px; margin-right: 15px; background: ${t.completed ? '#0aff0a' : 'transparent'};"></span>
              <span style="${t.completed ? 'text-decoration: line-through;' : ''} font-size: 18px;">${t.text}</span>
            </li>
          `).join('')}
        </ul>
        
        <div style="margin-top: 40px; text-align: right; color: #333; font-size: 12px; text-transform: uppercase;">
          Generated by Daily Tracker
        </div>
      </div>
    `
        document.body.appendChild(report)

        try {
            const canvas = await html2canvas(report, { backgroundColor: '#000000' })
            const link = document.createElement('a')
            link.download = `execution-report-${new Date().toISOString().split('T')[0]}.png`
            link.href = canvas.toDataURL()
            link.click()
        } finally {
            document.body.removeChild(report)
        }
    }

    return (
        <div className="flex items-center justify-between px-8 py-6 border-t border-white/5 mt-auto bg-black/80 backdrop-blur-xl z-10 w-full mb-0">
            <button
                onMouseDown={handleResetStart}
                onMouseUp={handleResetEnd}
                onMouseLeave={handleResetEnd}
                onTouchStart={handleResetStart}
                onTouchEnd={handleResetEnd}
                className="relative group flex items-center space-x-3 text-white/50 hover:text-white transition-colors"
            >
                <div className="relative flex items-center justify-center">
                    <RotateCw size={20} className={resetting ? "animate-spin text-neon-red" : ""} />
                    {resetting && (
                        <svg className="absolute w-8 h-8 pointer-events-none rotate-[-90deg]">
                            <circle
                                cx="16" cy="16" r="14" fill="none" stroke="#ff003c" strokeWidth="2"
                                strokeDasharray="88"
                                strokeDashoffset="88"
                                style={{ animation: 'dash 1.5s linear forwards' }}
                            />
                            <style jsx>{`
                        @keyframes dash { to { stroke-dashoffset: 0; } }
                    `}</style>
                        </svg>
                    )}
                </div>
                <span className="text-xs font-bold uppercase tracking-widest">
                    {resetting ? "Hold..." : "Reset Day"}
                </span>
            </button>

            <button
                onClick={handleDownload}
                className="flex items-center space-x-2 text-white/50 hover:text-neon-blue transition-colors"
            >
                <span className="text-xs font-bold uppercase tracking-widest">Report</span>
                <Download size={20} />
            </button>
        </div>
    )
}
